export enum Tokens {
  ACCESS_TOKEN_ENV_NAME = 'JWT_ACCESS_TOKEN_SECRET',
  ACCESS_EXPIRES_IN_TOKEN_ENV_NAME = 'JWT_ACCESS_TOKEN_EXPIRES_IN',
  REFRESH_TOKEN = 'refresh_token',
  REFRESH_TOKEN_ENV_NAME = 'JWT_REFRESH_TOKEN_SECRET',
  REFRESH_EXPIRES_IN_TOKEN_ENV_NAME = 'JWT_REFRESH_TOKEN_EXPIRES_IN',
}
